DASD-16431 - Update Windows Deploy Image to fix errors

diff --git a/Windows/Deploy/Image/Dockerfile b/Windows/Deploy/Image/Dockerfile
--- a/Windows/Deploy/Image/Dockerfile
+++ b/Windows/Deploy/Image/Dockerfile
@@ -27,14 +27,19 @@ RUN choco install mongodb --version 5.0.3 --confirm --limit-output --timeout 216
 # Add mongodb, sqlpackage and azcopy to the system path
 RUN setx /M PATH "%PATH%;%ProgramFiles%\MongoDB\Server\5.0\bin;%ProgramFiles%\sqlpackage;%ProgramFiles%\azcopy"
 
-SHELL ["pwsh", "-NoProfile", "-Command"]
+# Diagnostic: fail fast with the pwsh version, module paths and any crash details from the Application event log.
+RUN pwsh -NoProfile -NonInteractive -Command "$PSVersionTable | Out-String; $env:PSModulePath -split ';'; Import-Module Microsoft.PowerShell.Archive, PackageManagement, PowerShellGet -Verbose; Get-Module | Format-Table Name, Version, Path -AutoSize | Out-String -Width 300; Find-Module Pester -RequiredVersion 4.10.1 | Out-String" \
+  || (echo ===== pwsh failed, dumping Application event log ===== \
+  & powershell -NoProfile -Command "Get-WinEvent -FilterHashtable @{LogName='Application'; Level=1,2,3} -MaxEvents 10 -ErrorAction SilentlyContinue | Format-List TimeCreated, ProviderName, Id, Message" \
+  & exit 1)
+
+SHELL ["pwsh", "-NoProfile", "-NonInteractive", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 RUN Invoke-WebRequest -Uri 'https://aka.ms/sqlpackage-windows' -OutFile '.\sqlpackage.zip' -UseBasicParsing; New-Item -ItemType Directory -Force -Path 'C:\Program Files\sqlpackage' | Out-Null; tar.exe -xf '.\sqlpackage.zip' -C 'C:\Program Files\sqlpackage'; Remove-Item '.\sqlpackage.zip'
 RUN Invoke-WebRequest -Uri 'https://aka.ms/downloadazcopy-v10-windows' -OutFile '.\azcopy.zip' -UseBasicParsing; New-Item -ItemType Directory -Force -Path 'C:\Program Files\azcopy' | Out-Null; tar.exe -xf '.\azcopy.zip' -C 'C:\Program Files\azcopy'; Remove-Item '.\azcopy.zip'; Move-Item 'C:\Program Files\azcopy\azcopy_windows_amd64_*\azcopy.exe' 'C:\Program Files\azcopy\azcopy.exe'; Remove-Item 'C:\Program Files\azcopy\azcopy_windows_amd64_*' -Recurse -Force
 RUN Invoke-WebRequest -Uri 'https://aka.ms/installazurecliwindowsx64' -OutFile '.\AzureCLI.msi' -UseBasicParsing; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; Remove-Item '.\AzureCLI.msi'
 RUN Invoke-WebRequest -Uri 'https://aka.ms/dacfx-msi' -OutFile '.\dacfx.msi' -UseBasicParsing; Start-Process msiexec.exe -Wait -ArgumentList '/I dacfx.msi /quiet'; Remove-Item '.\dacfx.msi'
-RUN Install-PackageProvider -Name NuGet -Force
-RUN Install-Module Az -Force
-RUN Install-Module SqlServer, AzTable, AWSPowerShell.NetCore, PSScriptAnalyzer -Force
+RUN Install-Module Az -Scope AllUsers -Force
+RUN Install-Module SqlServer, AzTable, AWSPowerShell.NetCore, PSScriptAnalyzer -Scope AllUsers -Force
 RUN Install-Module Pester -RequiredVersion 4.10.1 -Scope AllUsers -Force
 
 SHELL ["powershell", "-NoProfile", "-Command"]
